name: smallvendors
description: "Small Vendors Catalog App - Digital catalog for small businesses"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  qr_flutter: 4.1.0
  uuid: ^4.5.3
  intl: ^0.20.2
  fl_chart: ^1.1.1
  csv: 6.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  image_picker: ^1.0.4
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  appwrite: ^21.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
